### ISSUE TITLE
在使用VUX的时候，在浏览器里可以，但真机运行的时候就会报错

### ISSUE THREAD

**Issue by webKity** [aOrz/vue-template-for-hbuilder#2]
在使用VUX的时候，在浏览器里可以，但真机运行的时候就会报错，错误如下：
 Uncaught SyntaxError: Unexpected token = at index.html:1

**Comment by aOrz** [comment]
有出错的 demo 工程吗

**Comment by webKity** [comment]
是webpack配置的问题，我用vux的webpack.base.conf.js替换了原来的就好了，你这个模板真的不错，你把它发布到NPM上去啊，这样用起来就方便多了，谢谢O(∩_∩)O~

**Comment by aOrz** [comment]
配置模板放 NPM 不太合适
