### ISSUE TITLE
非常感谢您的分享，请问您是怎么改dev模式使其可以在hbuilder里真机运行的？

### ISSUE THREAD

**Issue by JGS0601** [aOrz/vue-template-for-hbuilder#5]
目前在用webpack+vue开发手机app项目，打包用的hbuilder IDE，但就是builder之后每次移动替换太麻烦也会有白屏问题，一直困扰无法解决，希望能得到指点。

**Comment by aOrz** [comment]
实现的原理就是将dev模式下实时编译的结果保存到dist文件夹中，使用hbuilder打开dist文件夹，这样就可以利用hbuilder将更新的文件同步到调试app中，实现热更新

**Comment by aOrz** [comment]
具体的实现可以看下我的这篇文章 [https://fddcn.cn/wxmp-2.html](https://fddcn.cn/wxmp-2.html)   ，不知道是不是get到了你的问题的要点。
