### ISSUE TITLE
将Vux项目导入过后，样式全乱了

### ISSUE THREAD

**Issue by Jvaeyhcd** [aOrz/vue-template-for-hbuilder#7]
项目本来是使用Vux开发的，使用本模板将Vux打包成builder发现样式全都变了，请问是怎么回事呀？

**Comment by aOrz** [comment]
使用 Vux 需要特殊的 webpack 配置？

**Comment by stjw7098** [comment]
老哥，项目怎么调用原生api，想调用支付不知道怎么搞

**Comment by stjw7098** [comment]
hbuilder的h5+Api不能调

**Comment by Jvaeyhcd** [comment]
@aOrz @stjw7098 已经解决了，样式乱了是应为Mui的样式与Vux的样式有冲突的，地方，我去掉Mui的样式引用就可以了。
